/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      colors: {
        "surface-container": "#1a1919",
        "surface-tint": "#ff906d",
        "error-dim": "#d7383b",
        "tertiary-fixed": "#ff9655",
        "on-primary-fixed-variant": "#571400",
        "secondary-dim": "#d6d4d3",
        "on-primary-container": "#460f00",
        "surface-container-high": "#201f1f",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed": "#000000",
        "primary-fixed-dim": "#ff5d26",
        "on-secondary-container": "#d2d0cf",
        "on-surface-variant": "#adaaaa",
        "tertiary-fixed-dim": "#f6853b",
        "on-secondary": "#525151",
        "secondary-fixed-dim": "#d6d4d3",
        "on-tertiary-fixed-variant": "#612900",
        "inverse-on-surface": "#565555",
        "primary-container": "#ff784d",
        "on-error-container": "#ffa8a3",
        "error-container": "#9f0519",
        "surface": "#0e0e0e",
        "on-tertiary": "#572400",
        "tertiary": "#ff9a5d",
        "surface-container-lowest": "#000000",
        "outline": "#767575",
        "secondary": "#e5e2e1",
        "on-tertiary-fixed": "#2d0f00",
        "primary-dim": "#ff7346",
        "on-error": "#490006",
        "tertiary-container": "#f9873e",
        "surface-container-low": "#131313",
        "primary": "#ff906d",
        "surface-container-highest": "#262626",
        "on-secondary-fixed": "#403f3f",
        "error": "#ff716c",
        "background": "#0e0e0e",
        "inverse-primary": "#af3200",
        "surface-bright": "#2c2c2c",
        "on-primary": "#5b1600",
        "tertiary-dim": "#ef8037",
        "outline-variant": "#484847",
        "on-background": "#ffffff",
        "inverse-surface": "#fcf9f8",
        "on-tertiary-container": "#451b00",
        "on-surface": "#ffffff",
        "surface-dim": "#0e0e0e",
        "primary-fixed": "#ff784d",
        "surface-variant": "#262626",
        "on-secondary-fixed-variant": "#5c5b5b",
        "secondary-container": "#474746",
        
        // Legacy fallbacks so existing UI doesn't completely break
        "primary_container": "#f9873e",
        "tertiary_container": "#f9873e",
        "on_primary_container": "#460f00",
        "on_surface": "#ffffff",
        "on_surface_variant": "#adaaaa",
        "outline_variant": "#484847",
        "error_dim": "#d7383b",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem"},
    },
  },
  plugins: [],
}
