/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      colors: {
        // Material Design 3 Tokens - Dark Mode (defaults)
        "surface-container": "light-dark(#f3ede8, #1a1919)",
        "surface-tint": "#ff906d",
        "error-dim": "light-dark(#f9dedc, #d7383b)",
        "tertiary-fixed": "light-dark(#ffc393, #ff9655)",
        "on-primary-fixed-variant": "#571400",
        "secondary-dim": "light-dark(#f9f8f6, #d6d4d3)",
        "on-primary-container": "#460f00",
        "surface-container-high": "light-dark(#ede7e3, #201f1f)",
        "secondary-fixed": "light-dark(#f9f8f6, #e5e2e1)",
        "on-primary-fixed": "#000000",
        "primary-fixed-dim": "light-dark(#ffb373, #ff5d26)",
        "on-secondary-container": "light-dark(#5c5b5b, #d2d0cf)",
        "on-surface-variant": "light-dark(#52525b, #adaaaa)",
        "tertiary-fixed-dim": "light-dark(#ffb373, #f6853b)",
        "on-secondary": "light-dark(#ffffff, #525151)",
        "secondary-fixed-dim": "light-dark(#e8e2dd, #d6d4d3)",
        "on-tertiary-fixed-variant": "#612900",
        "inverse-on-surface": "light-dark(#f4eff4, #565555)",
        "primary-container": "light-dark(#ffdbce, #ff784d)",
        "on-error-container": "light-dark(#410e0b, #ffa8a3)",
        "error-container": "light-dark(#f9dedc, #9f0519)",
        "surface": "light-dark(#fffbfe, #0e0e0e)",
        "on-tertiary": "light-dark(#ffffff, #572400)",
        "tertiary": "light-dark(#d47f47, #ff9a5d)",
        "surface-container-lowest": "light-dark(#ffffff, #000000)",
        "outline": "light-dark(#a1a1aa, #767575)",
        "secondary": "light-dark(#726f6e, #e5e2e1)",
        "on-tertiary-fixed": "#6b2c00",
        "primary-dim": "light-dark(#ff7346, #ff7346)",
        "on-error": "light-dark(#ffffff, #490006)",
        "tertiary-container": "light-dark(#ffdcc8, #f9873e)",
        "surface-container-low": "light-dark(#f8f2f7, #131313)",
        "primary": "light-dark(#ff906d, #ff906d)",
        "surface-container-highest": "light-dark(#e8e2dd, #262626)",
        "on-secondary-fixed": "#403f3f",
        "error": "light-dark(#b3261e, #ff716c)",
        "background": "light-dark(#fffbfe, #0e0e0e)",
        "inverse-primary": "#af3200",
        "surface-bright": "light-dark(#fffbfe, #2c2c2c)",
        "on-primary": "light-dark(#ffffff, #5b1600)",
        "tertiary-dim": "light-dark(#d46939, #ef8037)",
        "outline-variant": "light-dark(#e4e4e7, #484847)",
        "on-background": "light-dark(#18181b, #ffffff)",
        "inverse-surface": "light-dark(#18181b, #fcf9f8)",
        "on-tertiary-container": "light-dark(#451b00, #451b00)",
        "on-surface": "light-dark(#18181b, #ffffff)",
        "surface-dim": "light-dark(#efe1e6, #0e0e0e)",
        "primary-fixed": "light-dark(#ffc393, #ff784d)",
        "surface-variant": "light-dark(#e4e4e7, #262626)",
        "on-secondary-fixed-variant": "#5c5b5b",
        "secondary-container": "light-dark(#f9f8f6, #474746)",
        
        // Legacy fallbacks so existing UI doesn't completely break
        "primary_container": "light-dark(#ffdbce, #f9873e)",
        "tertiary_container": "light-dark(#ffdcc8, #f9873e)",
        "on_primary_container": "#460f00",
        "on_surface": "light-dark(#18181b, #ffffff)",
        "on_surface_variant": "light-dark(#52525b, #adaaaa)",
        "outline_variant": "light-dark(#e4e4e7, #484847)",
        "error_dim": "light-dark(#f9dedc, #d7383b)",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"],
        "plus-jakarta-sans": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem"},
    },
  },
  plugins: [],
}
