<script setup lang="ts">
import { ref } from 'vue'
import { useAuthStore } from '@stores/auth'

const props = defineProps<{
  isOpen: boolean
}>()

const emit = defineEmits<{
  close: []
  verified: []
}>()

const authStore = useAuthStore()
const code = ref('')
const errorMsg = ref('')
const isVerifying = ref(false)

const handleVerify = async () => {
  if (code.value.length < 6) {
    errorMsg.value = 'Please enter a 6-digit code'
    return
  }
  isVerifying.value = ref(true).value
  errorMsg.value = ''
  try {
    const success = await authStore.verify2FA(code.value)
    if (success) {
      emit('verified')
    }
  } catch (err: any) {
    errorMsg.value = err.response?.data?.detail || err.message || 'Invalid verification code'
  } finally {
    isVerifying.value = false
  }
}

const handleCancel = () => {
  authStore.requires2FA = false
  authStore.challengeToken = null
  emit('close')
}
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition-all duration-300 ease-out"
      enter-from-class="opacity-0 scale-95 translate-y-4 blur-[4px]"
      enter-to-class="opacity-100 scale-100 translate-y-0 blur-0"
      leave-active-class="transition-all duration-300 ease-in"
      leave-from-class="opacity-100 scale-100 translate-y-0 blur-0"
      leave-to-class="opacity-0 scale-95 translate-y-4 blur-[4px]"
    >
      <div
        v-if="isOpen"
        class="fixed inset-0 z-[220] flex items-center justify-center p-4"
      >
        <!-- Backdrop -->
        <div class="absolute inset-0 bg-on-surface/40 dark:bg-on-surface/80" @click="handleCancel" />

        <!-- Modal Card -->
        <div class="relative w-full max-w-md glass-heavy rounded-3xl shadow-2xl overflow-hidden flex flex-col p-8 space-y-6">
          <div class="h-2 w-full bg-primary absolute top-0 left-0"></div>

          <div class="text-center space-y-2 mt-4">
            <div class="size-16 bg-primary/10 border border-primary/20 rounded-2xl flex items-center justify-center text-primary mx-auto shadow-inner">
              <span class="material-symbols-outlined text-3xl">security</span>
            </div>
            <h2 class="text-2xl font-semibold text-on-surface dark:text-on-surface tracking-tight">Two-Factor Verification</h2>
            <p class="text-on-surface-variant dark:text-on-surface-variant text-sm font-medium leading-relaxed px-4">
              Enter the verification code generated by your authenticator app to complete sign-in.
            </p>
          </div>

          <form @submit.prevent="handleVerify" class="space-y-6">
            <div class="space-y-2">
              <label class="block text-xs uppercase text-on-surface-variant dark:text-on-surface-variant font-bold text-center">
                6-Digit Verification Code
              </label>
              <input
                v-model="code"
                type="text"
                maxlength="8"
                pattern="[0-9]*"
                inputmode="numeric"
                required
                autocomplete="one-time-code"
                placeholder="000000"
                class="input text-center"
                @input="code = code.replace(/[^0-9]/g, '')"
              />
            </div>

            <p v-if="errorMsg" class="text-error dark:text-error text-sm text-center font-bold">{{ errorMsg }}</p>

            <div class="flex gap-4">
              <button
                type="button"
                class="flex-1 h-14 rounded-2xl bg-on-surface/5 dark:bg-on-surface/5 text-on-surface-variant dark:text-on-surface-variant font-bold text-xs uppercase hover:text-on-surface dark:hover:text-on-surface transition-colors border border-on-surface/5 dark:border-on-surface/5"
                @click="handleCancel"
              >
                Cancel
              </button>
              <button
                type="submit"
                :disabled="isVerifying || code.length < 6"
                class="flex-1 h-14 bg-primary text-on-primary font-semibold rounded-2xl text-xs uppercase transition-all hover:scale-[1.02] active:scale-95 disabled:opacity-50 disabled:scale-100 flex items-center justify-center gap-2"
              >
                <span v-if="isVerifying" class="material-symbols-outlined animate-spin text-sm">progress_activity</span>
                {{ isVerifying ? 'Verifying...' : 'Verify' }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>
